##################################################################
###########   .github/workflows/Megafirs-test.yml
##################################################################
name: Build And Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
     - cron: '0 0 * * *'
jobs: 
jobs:

    strategy:
      matrix:
        D1: [0,1,2]
        D2: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
      fail-fast: false
    steps:
    - name: Run checkout@v2.3.4
      uses: actions/checkout@v2.3.4

    - name: Build
      run: |
       
        echo "done"
    - name: Test
      run: |
        rm -rf *
        echo "done"  
